/**
 * Demo fallback data for RazorFlow Ops
 * Used when backend API is unavailable (Vercel deployment without backend)
 */

const now = new Date();
const hoursAgo = (h) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();

export const demoDashboard = {
  _demo: true,
  merchant_id: "11111111-1111-1111-1111-111111111111",
  merchant_name: "QuickCommerce India",
  critical_anomalies: [
    {
      id: "demo-anom-1",
      anomaly_type: "settlement_delayed",
      severity: "critical",
      detected_at: daysAgo(3),
      root_cause: "insufficient_funds",
      root_cause_confidence: 0.92,
      related_settlement_id: "demo-sett-1",
      details: "Settlement of Rs 2,45,000 delayed by 5 days. Bank returned insufficient funds error (code 40091).",
      recommendation: "Contact bank to verify settlement account balance and request expedited processing.",
      urgency: "critical",
      timeline: "24_hours",
      success_probability: 0.85,
      status: "open",
    },
    {
      id: "demo-anom-2",
      anomaly_type: "settlement_failed",
      severity: "critical",
      detected_at: daysAgo(2),
      root_cause: "bank_processing_delay",
      root_cause_confidence: 0.88,
      related_settlement_id: "demo-sett-2",
      details: "Settlement of Rs 1,80,000 failed after 3 retry attempts. Bank processing delay detected.",
      recommendation: "Wait for bank processing to complete. Typically resolves by T+2 EOD.",
      urgency: "high",
      timeline: "48_hours",
      success_probability: 0.90,
      status: "open",
    },
    {
      id: "demo-anom-3",
      anomaly_type: "refund_stuck",
      severity: "critical",
      detected_at: daysAgo(5),
      root_cause: "bank_processing_delay",
      root_cause_confidence: 0.85,
      related_refund_id: "demo-ref-1",
      details: "Refund of Rs 8,500 stuck for 5 days. Customer has filed dispute due to non-receipt.",
      recommendation: "Escalate to bank support immediately. Provide refund reference ID.",
      urgency: "critical",
      timeline: "immediate",
      success_probability: 0.70,
      status: "open",
    },
    {
      id: "demo-anom-4",
      anomaly_type: "dispute_deadline_risk",
      severity: "critical",
      detected_at: daysAgo(1),
      root_cause: "evidence_incomplete",
      root_cause_confidence: 0.95,
      related_dispute_id: "demo-disp-1",
      details: "Dispute of Rs 15,000 has evidence deadline in 2 days. Only 20% evidence uploaded.",
      recommendation: "Upload proof of delivery and customer communication immediately.",
      urgency: "critical",
      timeline: "48_hours",
      success_probability: 0.45,
      status: "open",
    },
    {
      id: "demo-anom-5",
      anomaly_type: "settlement_partial",
      severity: "critical",
      detected_at: hoursAgo(18),
      root_cause: "fee_mismatch",
      root_cause_confidence: 0.80,
      related_settlement_id: "demo-sett-3",
      details: "Settlement amount Rs 3,20,000 is 12% less than expected Rs 3,64,000. Fee overcharge detected.",
      recommendation: "Review fee calculation. If discrepancy persists, contact Razorpay support with settlement ID.",
      urgency: "high",
      timeline: "24_hours",
      success_probability: 0.75,
      status: "open",
    },
  ],
  warning_anomalies: [
    {
      id: "demo-anom-6",
      anomaly_type: "settlement_fee_mismatch",
      severity: "warning",
      detected_at: hoursAgo(8),
      root_cause: "fee_calculation_discrepancy",
      root_cause_confidence: 0.75,
      related_settlement_id: "demo-sett-4",
      details: "Fee charged Rs 2,000 vs expected Rs 1,600 (25% overcharge).",
      recommendation: "Review fee calculation and contact Razorpay if discrepancy persists.",
      urgency: "medium",
      timeline: "48_hours",
      success_probability: 0.70,
      status: "open",
    },
    {
      id: "demo-anom-7",
      anomaly_type: "refund_processing_delay",
      severity: "warning",
      detected_at: daysAgo(3),
      root_cause: "processing_delay",
      root_cause_confidence: 0.70,
      related_refund_id: "demo-ref-2",
      details: "Refund of Rs 3,200 in processing state for 3+ days. Expected completion T+3.",
      recommendation: "Monitor for 24 more hours. If not completed, contact bank.",
      urgency: "medium",
      timeline: "24_hours",
      success_probability: 0.80,
      status: "open",
    },
    {
      id: "demo-anom-8",
      anomaly_type: "settlement_multiple_failures",
      severity: "warning",
      detected_at: daysAgo(1),
      root_cause: "account_issue",
      root_cause_confidence: 0.82,
      related_settlement_id: "demo-sett-5",
      details: "Settlement failed 2 consecutive times. Possible account-level issue.",
      recommendation: "Verify settlement account details are correct and account is active.",
      urgency: "medium",
      timeline: "48_hours",
      success_probability: 0.65,
      status: "open",
    },
  ],
  info_anomalies: [
    {
      id: "demo-anom-9",
      anomaly_type: "settlement_reconciliation_gap",
      severity: "info",
      detected_at: hoursAgo(6),
      root_cause: "timing_difference",
      root_cause_confidence: 0.60,
      related_settlement_id: "demo-sett-6",
      details: "Minor reconciliation gap of Rs 450 between expected and actual settlement.",
      recommendation: "Likely timing difference. Will auto-resolve within 24 hours.",
      urgency: "low",
      timeline: "24_hours",
      success_probability: 0.95,
      status: "open",
    },
  ],
  top_recommendations: [
    {
      id: "demo-rec-1",
      anomaly_id: "demo-anom-1",
      recommended_action: "contact_bank",
      recommendation_text: "Contact your bank's corporate banking desk to verify settlement account has sufficient balance for NEFT credits. Reference settlement ID: settle_56703ca7a4.",
      urgency: "critical",
      timeline: "24_hours",
      expected_resolution_time_hours: 24,
      success_probability: 0.85,
    },
    {
      id: "demo-rec-2",
      anomaly_id: "demo-anom-4",
      recommended_action: "upload_evidence",
      recommendation_text: "Upload proof of delivery (tracking URL or signed receipt) and customer communication logs for dispute disp_8921f4a3b2. Deadline in 48 hours.",
      urgency: "critical",
      timeline: "48_hours",
      expected_resolution_time_hours: 48,
      success_probability: 0.45,
    },
    {
      id: "demo-rec-3",
      anomaly_id: "demo-anom-2",
      recommended_action: "wait_for_processing",
      recommendation_text: "Bank is processing the settlement transfer. Typically completes by T+2 EOD. No action required — will auto-resolve.",
      urgency: "high",
      timeline: "48_hours",
      expected_resolution_time_hours: 48,
      success_probability: 0.90,
    },
    {
      id: "demo-rec-4",
      anomaly_id: "demo-anom-3",
      recommended_action: "escalate_to_razorpay",
      recommendation_text: "Refund stuck for 5 days. Escalate to Razorpay support immediately with refund reference and customer communication. Urgent — customer has filed dispute.",
      urgency: "critical",
      timeline: "immediate",
      expected_resolution_time_hours: 2,
      success_probability: 0.70,
    },
  ],
  impact_summary: {
    time_saved_hours: 12.5,
    revenue_recovered: 45000,
    chargebacks_prevented: 3,
    total_anomalies: 9,
    resolved_this_month: 7,
  },
  next_deadline: new Date(now.getTime() + 2 * 86400000).toISOString(),
  summary: {
    total_anomalies: 9,
    critical_count: 5,
    warning_count: 3,
    info_count: 1,
  },
};

export const demoSettlement = {
  id: "demo-sett-1",
  amount: 245000,
  currency: "INR",
  status: "delayed",
  created_at: daysAgo(5),
  expected_arrival_at: daysAgo(3),
  actual_arrival_at: null,
  fees: 4900,
  taxes: 882,
  net_amount: 239218,
  diagnosis: {
    root_cause: "insufficient_funds",
    confidence: 0.92,
    explanation: "Your settlement account did not have sufficient balance when Razorpay attempted the NEFT transfer on the expected date. This is the most common cause of settlement delays.",
    causal_chain: [
      "Razorpay initiated NEFT transfer on " + daysAgo(3),
      "Bank returned code 40091: Insufficient Funds",
      "Automatic retry scheduled for next business day",
      "Settlement still pending — 5 days delayed",
    ],
  },
  recommendation: {
    action: "contact_bank",
    text: "Contact your bank's corporate banking desk to verify your settlement account has sufficient balance. Provide the settlement reference ID.",
    urgency: "critical",
    timeline: "24_hours",
    success_probability: 0.85,
    next_check: new Date(now.getTime() + 24 * 3600000).toISOString(),
  },
  attempts: [
    { attempt_number: 1, method: "NEFT", status: "failed", response_code: "40091", response_message: "Insufficient Funds", initiated_at: daysAgo(3) },
    { attempt_number: 2, method: "NEFT", status: "pending", initiated_at: daysAgo(1) },
  ],
};

export const demoRefund = {
  id: "demo-ref-1",
  amount: 8500,
  currency: "INR",
  status: "processing",
  reason: "customer_requested",
  created_at: daysAgo(5),
  expected_completion_at: daysAgo(2),
  actual_completion_at: null,
  initiated_by: "merchant",
  diagnosis: {
    root_cause: "bank_processing_delay",
    confidence: 0.85,
    explanation: "The refund has been initiated but the bank processing is taking longer than expected. This typically resolves within 5-7 business days for NEFT refunds.",
  },
  recommendation: {
    action: "escalate_to_razorpay",
    text: "Refund stuck for 5 days. Escalate to Razorpay support with refund ID and customer communication. Customer has filed a dispute — urgency is critical.",
    urgency: "critical",
    timeline: "immediate",
    success_probability: 0.70,
  },
};

export const demoDispute = {
  id: "demo-disp-1",
  type: "chargeback",
  reason_code: "4855",
  reason_text: "Goods/Services Not Received",
  amount: 15000,
  filed_at: daysAgo(5),
  evidence_deadline: new Date(now.getTime() + 2 * 86400000).toISOString(),
  current_status: "evidence_pending",
  evidence_completeness: 0.20,
  win_probability: 0.45,
  required_evidence: [
    { type: "proof_of_delivery", required: true, status: "missing", examples: ["Tracking URL with delivery confirmation", "Signed proof of delivery"] },
    { type: "customer_communication", required: true, status: "found", examples: ["Email thread confirming delivery"] },
    { type: "invoice", required: true, status: "missing", examples: ["Original invoice with item details"] },
    { type: "terms_of_service", required: false, status: "missing", examples: ["Link to terms page"] },
  ],
  diagnosis: {
    root_cause: "evidence_incomplete",
    confidence: 0.95,
    explanation: "Customer filed a chargeback claiming goods were not received. Only 20% of required evidence has been uploaded. You need proof of delivery to contest this.",
  },
  recommendation: {
    action: "upload_evidence",
    text: "Upload proof of delivery (tracking number, signed receipt) and original invoice within 48 hours to contest this chargeback.",
    urgency: "critical",
    timeline: "48_hours",
    success_probability: 0.45,
  },
};

export const demoMetrics = {
  time_saved_hours: 12.5,
  chargebacks_won: 3,
  revenue_recovered: 45000,
  detection_accuracy: 0.91,
  diagnosis_accuracy: 0.87,
  action_success_rate: 0.82,
  disputes_won: 7,
  disputes_total: 10,
  win_rate_with_agent: 0.70,
  win_rate_baseline: 0.45,
  recommendations_made: 24,
  recommendations_followed: 18,
  recommendations_succeeded: 15,
  period_days: 30,
};
