const now = new Date();
const hoursAgo = (h) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();

export const demoCommandCenter = {
  _demo: true,
  merchant: {
    name: "QuickCommerce India",
    plan: "Growth",
    autopilot_enabled: true,
  },
  kpis: {
    settlements_optimized: 47,
    cost_saved: 23500,
    disputes_automated: 12,
    disputes_won: 9,
    time_saved_hours: 34.5,
    chargebacks_prevented: 8,
    refunds_routed: 23,
    refund_savings: 4600,
  },
  automations: [
    {
      id: "auto-1",
      type: "settlement_routing",
      name: "Settlement Route Optimization",
      description: "Automatically routes settlements through NEFT/IMPS/RTGS based on cost, speed, and reliability",
      status: "active",
      last_run: hoursAgo(2),
      executions_today: 12,
      cost_saved_today: 3200,
      avg_savings_pct: 18,
      autopilot: true,
      metrics: {
        neft_routes: 8,
        imps_routes: 3,
        rtgs_routes: 1,
        avg_time_hours: 18,
        success_rate: 0.97,
      },
    },
    {
      id: "auto-2",
      type: "dispute_autopilot",
      name: "Dispute Evidence Autopilot",
      description: "Auto-gathers evidence, scores completeness, and submits claims when confidence > 80%",
      status: "active",
      last_run: hoursAgo(5),
      executions_today: 3,
      cost_saved_today: 15000,
      avg_savings_pct: 0,
      autopilot: true,
      metrics: {
        evidence_packets: 3,
        avg_completeness: 0.89,
        win_rate: 0.78,
        submitted_today: 2,
        pending_review: 1,
      },
    },
    {
      id: "auto-3",
      type: "refund_routing",
      name: "Smart Refund Routing",
      description: "Routes refunds through cheapest payment path based on refund type and customer history",
      status: "active",
      last_run: hoursAgo(1),
      executions_today: 8,
      cost_saved_today: 1600,
      avg_savings_pct: 12,
      autopilot: true,
      metrics: {
        wallet_routes: 5,
        bank_routes: 3,
        avg_completion_hours: 24,
        success_rate: 0.95,
      },
    },
    {
      id: "auto-4",
      type: "reconciliation",
      name: "Cross-Processor Reconciliation",
      description: "Reconciles transactions across all connected processors in real-time",
      status: "monitoring",
      last_run: hoursAgo(0.5),
      executions_today: 48,
      cost_saved_today: 0,
      avg_savings_pct: 0,
      autopilot: true,
      metrics: {
        transactions_matched: 342,
        discrepancies_found: 2,
        discrepancies_resolved: 2,
        processors_connected: 2,
      },
    },
  ],
  critical_operations: [
    {
      id: "op-1",
      type: "settlement_delayed",
      severity: "critical",
      title: "Settlement Route Blocked",
      description: "Rs 2,45,000 settlement blocked — NEFT returned insufficient funds. Auto-rerouting to IMPS.",
      amount: 245000,
      detected_at: hoursAgo(3),
      automation_status: "in_progress",
      estimated_savings: 650,
      confidence: 0.92,
    },
    {
      id: "op-2",
      type: "settlement_failed",
      severity: "critical",
      title: "Settlement Failed — Auto-Retry",
      description: "Rs 1,80,000 settlement failed after 3 attempts. Autopilot scheduling next business day retry.",
      amount: 180000,
      detected_at: daysAgo(1),
      automation_status: "automating",
      estimated_savings: 0,
      confidence: 0.88,
    },
    {
      id: "op-3",
      type: "refund_stuck",
      severity: "critical",
      title: "Refund Processing — Escalated",
      description: "Rs 8,500 refund stuck 5 days. Auto-escalated to Razorpay support with full documentation.",
      amount: 8500,
      detected_at: daysAgo(5),
      automation_status: "completed",
      estimated_savings: 0,
      confidence: 0.85,
    },
    {
      id: "op-4",
      type: "dispute_evidence",
      severity: "critical",
      title: "Dispute Evidence — Auto-Assembling",
      description: "Dispute Rs 15,000 deadline in 48h. Autopilot gathering proof of delivery + invoice.",
      amount: 15000,
      detected_at: daysAgo(2),
      automation_status: "in_progress",
      estimated_savings: 15000,
      confidence: 0.78,
    },
  ],
  processors: [
    { name: "Razorpay", status: "connected", last_sync: minutesAgo(2), transactions_today: 342 },
    { name: "Stripe", status: "connected", last_sync: minutesAgo(5), transactions_today: 128 },
  ],
  impact: {
    total_saved_this_month: 43100,
    total_saved_last_month: 38200,
    improvement_pct: 12.8,
    roi_months: 1.2,
    hours_saved_this_month: 34.5,
    chargebacks_won: 8,
    chargebacks_total: 11,
    win_rate: 0.727,
  },
  next_deadline: new Date(now.getTime() + 48 * 3600000).toISOString(),
};

function minutesAgo(m) {
  return new Date(now.getTime() - m * 60000).toISOString();
}

export const demoMetrics = {
  _demo: true,
  detection: {
    precision: 0.91,
    recall: 0.85,
    f1: 0.88,
    anomalies_detected: 42,
    anomalies_real: 38,
  },
  automation: {
    total_executions: 156,
    success_rate: 0.94,
    avg_execution_time_seconds: 12,
    settlements_routed: 47,
    disputes_submitted: 9,
    refunds_routed: 23,
  },
  financial: {
    cost_saved: 43100,
    cost_saved_trend: 12.8,
    revenue_recovered: 58000,
    revenue_trend: 22,
    avg_settlement_savings_pct: 18,
    avg_refund_savings_pct: 12,
  },
  disputes: {
    won: 8,
    total: 11,
    win_rate: 0.727,
    baseline_win_rate: 0.45,
    improvement: 61.6,
    evidence_packets: 11,
    avg_completeness: 0.89,
  },
  time: {
    hours_saved: 34.5,
    manual_tasks_automated: 89,
    avg_time_per_task_minutes: 23,
  },
};
